source "https://rubygems.org"
ruby '2.5.1'
#gem 'rspec'
gem 'pry'
#gem 'rubocop', '~> 0.57.2'
gem 'dotenv'
#gem 'twitter'
gem 'nokogiri'
#gem 'rubysl-open-uri'
#gem 'open-uri'
#gem 'restclient'
gem 'csv'
gem 'sinatra'
gem 'shotgun'



